/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.68
 * Generated at: 2022-10-18 14:32:48 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.ArrayList;
import dto.Product;
import dao.ProductRepository;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("dto.Product");
    _jspx_imports_classes.add("dao.ProductRepository");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      dao.ProductRepository productDAO = null;
      synchronized (session) {
        productDAO = (dao.ProductRepository) _jspx_page_context.getAttribute("productDAO", javax.servlet.jsp.PageContext.SESSION_SCOPE);
        if (productDAO == null){
          productDAO = new dao.ProductRepository();
          _jspx_page_context.setAttribute("productDAO", productDAO, javax.servlet.jsp.PageContext.SESSION_SCOPE);
        }
      }
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"ko\">\n");
      out.write("<head>\n");
      out.write("	<meta charset=\"UTF-8\">\n");
      out.write("	<title>MLB-Statcast Database</title>\n");
      out.write("	<link rel=\"stylesheet\" type=\"text/css\" href=\"./xeicon/xeicon.min.css\">\n");
      out.write("	<link rel=\"stylesheet\" href=\"css/style.css\">\n");
      out.write("	<link rel=\"stylesheet\" href=\"css/swiper.min.css\">\n");
      out.write("	<link rel=\"stylesheet\" href=\"css/default.css\">\n");
      out.write("	<script src=\"js/jquery.js\" charset=\"utf-8\"></script>\n");
      out.write("	<script src=\"js/swiper.js\" charset=\"utf-8\"></script>\n");
      out.write("	<script src=\"js/default.js\" charset=\"utf-8\"></script>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("	<header>\n");
      out.write("		<div class=\"top clear\">\n");
      out.write("			<h1><a href=\"\"><img src=\"img/original_logo.png\" alt=\"original_logo\"></a><a href=\"#\"><img src=\"img/sub_logo.png\" alt=\"sub_logo\"></a></h1>\n");
      out.write("			<div>\n");
      out.write("				<div class=\"control\">\n");
      out.write("				<h2>Move to Homepage</h2>\n");
      out.write("				<ul>\n");
      out.write("					<li><button class=\"xi-plus\"><span class=\"hide\">크기확대</span></button></li>\n");
      out.write("					<li><button class=\"xi-minus\"><span class=\"hide\">크기축소</span></button></li>\n");
      out.write("					<li><button>Original Size</button></li>				\n");
      out.write("				</ul>\n");
      out.write("				</div>\n");
      out.write("			<h2 class=\"hide\">SNS</h2>\n");
      out.write("			<ul class=\"sns\">\n");
      out.write("				<li><a href=\"https://mlb.com\"><img src=\"img/sns_1.png\" alt =\"sns_1\"></a></li>\n");
      out.write("				<li><a href=\"#\"><img src=\"img/sns_2.png\" alt =\"sns_2\"></a></li>\n");
      out.write("				<li><a href=\"#\"><img src=\"img/sns_3.png\" alt =\"sns_3\"></a></li>\n");
      out.write("				<li><a href=\"#\"><img src=\"img/sns_4.png\" alt =\"sns_4\"></a></li>\n");
      out.write("			</ul>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("		<div class=\"btm\">\n");
      out.write("			<div class=\"clear\">\n");
      out.write("				<nav class=\"lnb\">\n");
      out.write("					<ul>\n");
      out.write("						<li><a href=\"#a\">FAQ</a></li>\n");
      out.write("						<li><a href=\"#a\">Contact</a></li>\n");
      out.write("						<li><a href=\"#a\">Pitchers</a></li>\n");
      out.write("						<li><a href=\"#a\">Hitters</a></li>\n");
      out.write("						<li><a href=\"#a\">Figures</a></li>\n");
      out.write("					</ul>\n");
      out.write("				</nav>\n");
      out.write("				<div class=\"spot\">\n");
      out.write("					<a href=\"./login.jsp\">Login</a>\n");
      out.write("					<a href=\"./join01.jsp\">Sign up</a>\n");
      out.write("					<button onclick=\"alert('아직 미구현된 기능입니다.')\"> <i class=\"xi-search\"><span class=\"hide\">검색</span></i></button>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("		\n");
      out.write("	</header>\n");
      out.write("	<main>\n");
      out.write("		<section class=\"visual\">\n");
      out.write("			<h2 class=\"hide\"></h2>\n");
      out.write("			<div class=\"swiper-container slide1\">\n");
      out.write("      			<div class=\"swiper-wrapper\">\n");
      out.write("       					 <div class=\"swiper-slide\">\n");
      out.write("							\n");
      out.write("						   <img src=\"img/slide2_mlb.png\" alt=\"\">\n");
      out.write("                            <div class=\"hide\"> image1 </div>\n");
      out.write("                         </div>\n");
      out.write("        				<div class=\"swiper-slide\">\n");
      out.write("							<a href=\"\">\n");
      out.write("							<img src=\"img/slide3_mlb.png\" alt=\"\" />\n");
      out.write("							 <div class=\"hide\">\n");
      out.write("							 	image1\n");
      out.write("								</div>\n");
      out.write("							 </a>\n");
      out.write("						 </div>\n");
      out.write("      			</div>\n");
      out.write("				<div class=\"controls\">\n");
      out.write("      				<button class=\"next\"></button>\n");
      out.write("      				<button class=\"prev\"></button>\n");
      out.write("      				<div class=\"paging\"></div>\n");
      out.write("				</div>	\n");
      out.write("    		</div>\n");
      out.write("		</section>\n");
      out.write("\n");
      out.write("\n");
      out.write("		<section>\n");
      out.write("			<div class=\"main_text0\">\n");
      out.write("				<h1>WELCOME TO BASEBALL</h1>\n");
      out.write("				<div class=\"contents1\">메이저리그에 오신 여러분들을 환영합니다.</div>\n");
      out.write("\n");
      out.write("				<ul class=\"icons\">\n");
      out.write("					<li>\n");
      out.write("					\n");
      out.write("					");

						ProductRepository dao = ProductRepository.getInstance();
						ArrayList<Product> listOfProducts = productDAO.getAllProducts();
					
      out.write("\n");
      out.write("				\n");
      out.write("						<dl>\n");
      out.write("							");

								Product product = listOfProducts.get(0);
							
      out.write("\n");
      out.write("					\n");
      out.write("							<dt><a href=\"\">");
      out.print( product.getPename() );
      out.write("</a></dt>\n");
      out.write("							<dd><a href=\"\"><img src=\"images/");
      out.print( product.getFilename() );
      out.write("\" alt=\"\"></a></dd>\n");
      out.write("							<dd class=\"figure\">");
      out.print( product.getPname());
      out.write("</dd>\n");
      out.write("							<dd class=\"last\">\n");
      out.write("								<div><a href=\"./product.jsp?id=");
      out.print(product.getPid());
      out.write("\">이동하기</a></div>\n");
      out.write("								<div><a href=\"./addProduct.jsp?id=");
      out.print(product.getPid());
      out.write("\">등록하기</a></div>\n");
      out.write("							</dd>\n");
      out.write("						</dl>\n");
      out.write("					</li>\n");
      out.write("					<li>\n");
      out.write("						<dl>\n");
      out.write("						\n");
      out.write("							");

								Product product2 = listOfProducts.get(1);
							
      out.write("\n");
      out.write("							<dt><a href=\"\">");
      out.print( product2.getPename() );
      out.write("</a></dt>\n");
      out.write("							<dd><a href=\"\"><img src=\"img/mlb_figure_01.png\" alt=\"\"></a></dd>\n");
      out.write("							<dd class=\"figure\">");
      out.print( product2.getPname() );
      out.write("</dd>\n");
      out.write("							<dd class=\"last\">\n");
      out.write("								<div><a href=\"./product.jsp?id=");
      out.print(product.getPid());
      out.write("\">이동하기</a></div>\n");
      out.write("								<div><a href=\"./addProduct.jsp?id=");
      out.print(product.getPid());
      out.write("\">등록하기</a></div>\n");
      out.write("							</dd>\n");
      out.write("						</dl>\n");
      out.write("					</li>\n");
      out.write("					<li>\n");
      out.write("						<dl>\n");
      out.write("						\n");
      out.write("							");

								Product product3 = listOfProducts.get(2);
							
      out.write("\n");
      out.write("							<dt><a href=\"\">");
      out.print( product3.getPename() );
      out.write("</a></dt>\n");
      out.write("							<dd><a href=\"\"><img src=\"img/mlb_figure_01.png\" alt=\"\"></a></dd>\n");
      out.write("							<dd class=\"figure\">");
      out.print( product3.getPname() );
      out.write("</dd>\n");
      out.write("							<dd class=\"last\">\n");
      out.write("								<div><a href=\"./product.jsp?id=");
      out.print(product.getPid());
      out.write("\">이동하기</a></div>\n");
      out.write("								<div><a href=\"./addProduct.jsp?id=");
      out.print(product.getPid());
      out.write("\">등록하기</a></div>\n");
      out.write("							</dd>\n");
      out.write("						</dl>\n");
      out.write("					</li>\n");
      out.write("					\n");
      out.write("				</ul>\n");
      out.write("				\n");
      out.write("			</div>\n");
      out.write("		</section>\n");
      out.write("			\n");
      out.write("		<section>\n");
      out.write("			<div id=\"info\">\n");
      out.write("				<div>\n");
      out.write("				<h2>Sites Info.</h2>\n");
      out.write("				<ul class=\"list clear\">\n");
      out.write("					<li class=\"bg1\">\n");
      out.write("						<h3>사이트 원본 이동</h3>\n");
      out.write("						<div>곧 맨 위로 이동 됩니다.</div>\n");
      out.write("						<a href=\"#a\">바로가기</a>\n");
      out.write("					</li>\n");
      out.write("					<li class=\"bg2\">\n");
      out.write("						<a href=\"info.html\"></a>\n");
      out.write("						<h3>피규어 정보 이동</h3>\n");
      out.write("						<div>피규어 목록을 볼 수 있습니다.</div>\n");
      out.write("					</li>\n");
      out.write("					<li class=\"bg3\">\n");
      out.write("						<a href=\"geton.html\"></a>\n");
      out.write("						<h3>피규어 등록 이동</h3>\n");
      out.write("						<div>권한 있는 사람만 이동 가능합니다.</div>\n");
      out.write("					</li>\n");
      out.write("					<li class=\"bg4\">\n");
      out.write("						<a href=\"view.html\"></a>\n");
      out.write("						<h3>질문 게시판 이동</h3>\n");
      out.write("						<div>문의 게시판으로 이동합니다.</div>\n");
      out.write("					</li>\n");
      out.write("				</ul>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("		</section>\n");
      out.write("\n");
      out.write("	</main>\n");
      out.write("\n");
      out.write("	\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
