/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.68
 * Generated at: 2022-10-18 10:04:00 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import dto.Product;
import dao.ProductRepository;

public final class product_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("dto.Product");
    _jspx_imports_classes.add("dao.ProductRepository");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');
      out.write('\n');
      dao.ProductRepository productDAO = null;
      synchronized (session) {
        productDAO = (dao.ProductRepository) _jspx_page_context.getAttribute("productDAO", javax.servlet.jsp.PageContext.SESSION_SCOPE);
        if (productDAO == null){
          productDAO = new dao.ProductRepository();
          _jspx_page_context.setAttribute("productDAO", productDAO, javax.servlet.jsp.PageContext.SESSION_SCOPE);
        }
      }
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"ko\">\n");
      out.write("<head>\n");
      out.write("	<meta charset=\"UTF-8\">\n");
      out.write("	<title>MLB-Statcast Database</title>\n");
      out.write("	<link rel=\"stylesheet\" type=\"text/css\" href=\"xeicon/xeicon.min.css\">\n");
      out.write("	<link rel=\"stylesheet\" href=\"css/info.css\">\n");
      out.write("	<link rel=\"stylesheet\" href=\"css/swiper.min.css\">\n");
      out.write("	<link rel=\"stylesheet\" href=\"css/default.css\">\n");
      out.write("	<script src=\"js/jquery.js\" charset=\"utf-8\"></script>\n");
      out.write("	<script src=\"js/swiper.js\" charset=\"utf-8\"></script>\n");
      out.write("	<script src=\"js/default.js\" charset=\"utf-8\"></script>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("	<header>\n");
      out.write("		<div class=\"top clear\">\n");
      out.write("			<h1><a href=\"\"><img src=\"img/original_logo.png\" alt=\"original_logo\"></a><a href=\"#\"><img src=\"img/sub_logo.png\" alt=\"sub_logo\"></a></h1>\n");
      out.write("			<div>\n");
      out.write("				<div class=\"control\">\n");
      out.write("				<h2>Move to Homepage</h2>\n");
      out.write("				<ul>\n");
      out.write("					<li><button class=\"xi-plus\"><span class=\"hide\">크기확대</span></button></li>\n");
      out.write("					<li><button class=\"xi-minus\"><span class=\"hide\">크기축소</span></button></li>\n");
      out.write("					<li><button>Original Size</button></li>				\n");
      out.write("				</ul>\n");
      out.write("				</div>\n");
      out.write("			<h2 class=\"hide\">SNS</h2>\n");
      out.write("			<ul class=\"sns\">\n");
      out.write("				<li><a href=\"https://mlb.com\"><img src=\"../img/sns_1.png\" alt =\"sns_1\"></a></li>\n");
      out.write("				<li><a href=\"#\"><img src=\"img/sns_2.png\" alt =\"sns_2\"></a></li>\n");
      out.write("				<li><a href=\"#\"><img src=\"img/sns_3.png\" alt =\"sns_3\"></a></li>\n");
      out.write("				<li><a href=\"#\"><img src=\"img/sns_4.png\" alt =\"sns_4\"></a></li>\n");
      out.write("			</ul>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("		<div class=\"btm\">\n");
      out.write("			<div class=\"clear\">\n");
      out.write("				<nav class=\"lnb\">\n");
      out.write("					<ul>\n");
      out.write("						<li><a href=\"#a\">Player Stats</a></li>\n");
      out.write("						<li><a href=\"contact.html\">Contact</a></li>\n");
      out.write("						<li><a href=\"#a\">Position</a></li>\n");
      out.write("						<li><a href=\"#a\">Maps</a></li>\n");
      out.write("						<li><a href=\"#a\">FAQ</a></li>\n");
      out.write("					</ul>\n");
      out.write("				</nav>\n");
      out.write("				<div class=\"spot\">\n");
      out.write("					<a href=\"login.jsp\">Login</a>\n");
      out.write("					<a href=\"join1.jsp\">Sign up</a>\n");
      out.write("					<button onclick=\"alert('아직 미구현된 기능입니다.')\"> <i class=\"xi-search\"><span class=\"hide\">검색</span></i></button>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("		\n");
      out.write("	</header>\n");
      out.write("\n");
      out.write("    <main>\n");
      out.write("        ");

        	String id = request.getParameter("id");
        	ProductRepository dao = ProductRepository.getInstance();
         	Product product = productDAO.getProductById(id);
        
      out.write("\n");
      out.write("    \n");
      out.write("        <section class=\"block\">\n");
      out.write("            <div class=\"product_view\">\n");
      out.write("                <h2>");
      out.print( product.getPname() );
      out.write("</h2>\n");
      out.write("                <table>\n");
      out.write("                    \n");
      out.write("                    <colgroup>\n");
      out.write("                    <col style=\"width:173px;\">\n");
      out.write("                    <col>\n");
      out.write("                    </colgroup>\n");
      out.write("                    <tbody>\n");
      out.write("                    <tr>\n");
      out.write("                        <th>영어이름</th>\n");
      out.write("                        <td class=\"price\">");
      out.print( product.getPename() );
      out.write("</td>\n");
      out.write("                    </tr>\n");
      out.write("                    <tr>\n");
      out.write("                        <th>상품코드</th>\n");
      out.write("                        <td>");
      out.print( product.getPid() );
      out.write("</td>\n");
      out.write("                    </tr>\n");
      out.write("                    <tr>\n");
      out.write("                        <th>제조사/공급사</th>\n");
      out.write("                        <td>");
      out.print( product.getMan() );
      out.write("</td>\n");
      out.write("                    </tr>\n");
      out.write("                    \n");
      out.write("                    <tr>\n");
      out.write("                        <th>사용가능쿠폰</th>\n");
      out.write("                        <td>");
      out.print( product.getUnitcoupon() );
      out.write("</td>\n");
      out.write("                    </tr>\n");
      out.write("                    <tr>\n");
      out.write("                        <th>가격</th>\n");
      out.write("                        <td class=\"total\"><b>");
      out.print( product.getUnitprice() );
      out.write("</b>원</td>\n");
      out.write("                    </tr>\n");
      out.write("                    \n");
      out.write("                    </tbody>\n");
      out.write("                </table>\n");
      out.write("                <div class=\"img\">\n");
      out.write("                    <img src=\"images/");
      out.print( product.getFilename() );
      out.write("\" alt=\"\">\n");
      out.write("                </div>\n");
      out.write("                <div class=\"btns\">\n");
      out.write("                    <a href=\"#a\" class=\"btn1\">장바구니</a>\n");
      out.write("                    <a href=\"#a\" class=\"btn2\">구매하기</a>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        \n");
      out.write("        </section>\n");
      out.write("    </main>\n");
      out.write("\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>s");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
